# Generated by Django 3.2 on 2022-04-09 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aci_logs',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 12, 4, 34, 384074, tzinfo=utc)),
        ),
    ]
